## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("loan_approval_dataset.csv")
application_df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,Income_to_Loan,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status,loan_status1
0,1,2,Graduate,No,9600000,29900000,0.321070,12,778,2400000,17600000,22700000,8000000,Approved,1
1,2,0,Not Graduate,Yes,4100000,12200000,0.336066,8,417,2700000,2200000,8800000,3300000,Rejected,0
2,3,3,Graduate,No,9100000,29700000,0.306397,20,506,7100000,4500000,33300000,12800000,Rejected,0
3,4,3,Graduate,No,8200000,30700000,0.267101,8,467,18200000,3300000,23300000,7900000,Rejected,0
4,5,5,Not Graduate,Yes,9800000,24200000,0.404959,20,382,12400000,8200000,29400000,5000000,Rejected,0

In [2]:
print(application_df.head())

   loan_id  no_of_dependents     education self_employed  income_annum  \
0        1                 2      Graduate            No       9600000
1        2                 0  Not Graduate           Yes       4100000
2        3                 3      Graduate            No       9100000
3        4                 3      Graduate            No       8200000
4        5                 5  Not Graduate           Yes       9800000

   loan_amount  Income_to_Loan  loan_term  cibil_score  \
0     29900000        0.321070         12          778
1     12200000        0.336066          8          417
2     29700000        0.306397         20          506
3     30700000        0.267101          8          467
4     24200000        0.404959         20          382

   residential_assets_value  commercial_assets_value  luxury_assets_value  \
0                   2400000                 17600000             22700000
1                   2700000                  2200000              8800000
2                   7100000                  4500000             33300000
3                  18200000                  3300000             23300000
4                  12400000                  8200000             29400000

   bank_asset_value loan_status  loan_status1
0           8000000    Approved             1
1           3300000    Rejected             0
2          12800000    Rejected             0
3           7900000    Rejected             0
4           5000000    Rejected             0

In [3]:
# Look at cibil_score value counts for binning
cibil_score_counts = application_df['cibil_score'].value_counts()
print(cibil_score_counts)

348    16
543    15
538    15
778    14
509    14
       ..
334     2
773     2
893     2
484     2
864     1
Name: cibil_score, Length: 601, dtype: int64

In [4]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value = 4
rare_cibil_score = cibil_score_counts[cibil_score_counts < cutoff_value].index.tolist()
cibil_score_to_replace = rare_cibil_score

# Replace in dataframe
for app in cibil_score_to_replace:
    application_df['cibil_score'] = application_df['cibil_score'].replace(app,"Other")
# Check to make sure binning was successful
application_df['cibil_score'].value_counts()

Other    105
348       16
543       15
538       15
778       14
        ...
764        4
862        4
690        4
357        4
568        4
Name: cibil_score, Length: 565, dtype: int64

In [5]:
column_types = application_df.dtypes
print(column_types)

loan_id                       int64
no_of_dependents              int64
education                    object
self_employed                object
income_annum                  int64
loan_amount                   int64
Income_to_Loan              float64
loan_term                     int64
cibil_score                  object
residential_assets_value      int64
commercial_assets_value       int64
luxury_assets_value           int64
bank_asset_value              int64
loan_status                  object
loan_status1                  int64
dtype: object

In [6]:
# Convert categorical data to numeric with `pd.get_dummies`
categorical_columns = ['education', 'self_employed', 'cibil_score', 'loan_status']
application_df_encoded = pd.get_dummies(application_df, columns=categorical_columns) 
print(application_df_encoded.head())

   loan_id  no_of_dependents  income_annum  loan_amount  Income_to_Loan  \
0        1                 2       9600000     29900000        0.321070
1        2                 0       4100000     12200000        0.336066
2        3                 3       9100000     29700000        0.306397
3        4                 3       8200000     30700000        0.267101
4        5                 5       9800000     24200000        0.404959

   loan_term  residential_assets_value  commercial_assets_value  \
0         12                   2400000                 17600000
1          8                   2700000                  2200000
2         20                   7100000                  4500000
3          8                  18200000                  3300000
4         20                  12400000                  8200000

   luxury_assets_value  bank_asset_value  ...  cibil_score_894  \
0             22700000           8000000  ...                0
1              8800000           3300000  ...                0
2             33300000          12800000  ...                0
3             23300000           7900000  ...                0
4             29400000           5000000  ...                0

   cibil_score_895  cibil_score_896  cibil_score_897  cibil_score_898  \
0                0                0                0                0
1                0                0                0                0
2                0                0                0                0
3                0                0                0                0
4                0                0                0                0

   cibil_score_899  cibil_score_900  cibil_score_Other  loan_status_Approved  \
0                0                0                  0                     1
1                0                0                  0                     0
2                0                0                  0                     0
3                0                0                  0                     0
4                0                0                  0                     0

   loan_status_Rejected
0                     0
1                     1
2                     1
3                     1
4                     1

[5 rows x 582 columns]

In [7]:
# Split our preprocessed data into our features and target arrays
X = application_df_encoded.drop('loan_status_Approved', axis=1)  # Features
y = application_df_encoded['loan_status_Approved']  # Target

# Display the shapes of the arrays
print("Shape of features (X):", X.shape)
print("Shape of target (y):", y.shape)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

# Display the shapes of the datasets
print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of features (X): (4269, 581)
Shape of target (y): (4269,)
Shape of X_train: (3201, 581)
Shape of X_test: (1068, 581)
Shape of y_train: (3201,)
Shape of y_test: (1068,)

In [8]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [9]:
column_types = application_df_encoded.dtypes
print(column_types)
print(application_df_encoded.head())

loan_id                   int64
no_of_dependents          int64
income_annum              int64
loan_amount               int64
Income_to_Loan          float64
                         ...
cibil_score_899           uint8
cibil_score_900           uint8
cibil_score_Other         uint8
loan_status_Approved      uint8
loan_status_Rejected      uint8
Length: 582, dtype: object
   loan_id  no_of_dependents  income_annum  loan_amount  Income_to_Loan  \
0        1                 2       9600000     29900000        0.321070
1        2                 0       4100000     12200000        0.336066
2        3                 3       9100000     29700000        0.306397
3        4                 3       8200000     30700000        0.267101
4        5                 5       9800000     24200000        0.404959

   loan_term  residential_assets_value  commercial_assets_value  \
0         12                   2400000                 17600000
1          8                   2700000                  2200000
2         20                   7100000                  4500000
3          8                  18200000                  3300000
4         20                  12400000                  8200000

   luxury_assets_value  bank_asset_value  ...  cibil_score_894  \
0             22700000           8000000  ...                0
1              8800000           3300000  ...                0
2             33300000          12800000  ...                0
3             23300000           7900000  ...                0
4             29400000           5000000  ...                0

   cibil_score_895  cibil_score_896  cibil_score_897  cibil_score_898  \
0                0                0                0                0
1                0                0                0                0
2                0                0                0                0
3                0                0                0                0
4                0                0                0                0

   cibil_score_899  cibil_score_900  cibil_score_Other  loan_status_Approved  \
0                0                0                  0                     1
1                0                0                  0                     0
2                0                0                  0                     0
3                0                0                  0                     0
4                0                0                  0                     0

   loan_status_Rejected
0                     0
1                     1
2                     1
3                     1
4                     1

[5 rows x 582 columns]

## Compile, Train and Evaluate the Model

In [10]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = X_train.shape[1]

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=128, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=64, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Build the model
nn.build(input_shape=(None, input_features))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 128)               74496

 dense_1 (Dense)             (None, 64)                8256

 dense_2 (Dense)             (None, 1)                 65

=================================================================
Total params: 82817 (323.50 KB)
Trainable params: 82817 (323.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [11]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [12]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
101/101 [==============================] - 1s 4ms/step - loss: 0.3088 - accuracy: 0.8719
Epoch 2/100
101/101 [==============================] - 0s 3ms/step - loss: 0.0190 - accuracy: 0.9963
Epoch 3/100
101/101 [==============================] - 0s 3ms/step - loss: 0.0036 - accuracy: 0.9997
Epoch 4/100
101/101 [==============================] - 0s 4ms/step - loss: 0.0017 - accuracy: 0.9997
Epoch 5/100
101/101 [==============================] - 0s 3ms/step - loss: 0.0016 - accuracy: 0.9997
Epoch 6/100
101/101 [==============================] - 0s 4ms/step - loss: 0.0022 - accuracy: 0.9997
Epoch 7/100
101/101 [==============================] - 0s 3ms/step - loss: 4.2257e-04 - accuracy: 1.0000
Epoch 8/100
101/101 [==============================] - 0s 4ms/step - loss: 2.5014e-04 - accuracy: 1.0000
Epoch 9/100
101/101 [==============================] - 0s 3ms/step - loss: 1.9271e-04 - accuracy: 1.0000
Epoch 10/100
101/101 [==============================] - 0s 4ms/step - loss: 1.5443e-04 - accuracy: 1.0000
Epoch 11/100
101/101 [==============================] - 0s 3ms/step - loss: 1.2625e-04 - accuracy: 1.0000
Epoch 12/100
101/101 [==============================] - 0s 4ms/step - loss: 1.0560e-04 - accuracy: 1.0000
Epoch 13/100
101/101 [==============================] - 0s 4ms/step - loss: 8.8526e-05 - accuracy: 1.0000
Epoch 14/100
101/101 [==============================] - 0s 4ms/step - loss: 7.5800e-05 - accuracy: 1.0000
Epoch 15/100
101/101 [==============================] - 1s 6ms/step - loss: 6.5275e-05 - accuracy: 1.0000
Epoch 16/100
101/101 [==============================] - 0s 4ms/step - loss: 5.6647e-05 - accuracy: 1.0000
Epoch 17/100
101/101 [==============================] - 0s 4ms/step - loss: 4.9594e-05 - accuracy: 1.0000
Epoch 18/100
101/101 [==============================] - 0s 4ms/step - loss: 4.3818e-05 - accuracy: 1.0000
Epoch 19/100
101/101 [==============================] - 0s 4ms/step - loss: 3.8533e-05 - accuracy: 1.0000
Epoch 20/100
101/101 [==============================] - 0s 4ms/step - loss: 3.4479e-05 - accuracy: 1.0000
Epoch 21/100
101/101 [==============================] - 0s 4ms/step - loss: 3.0584e-05 - accuracy: 1.0000
Epoch 22/100
101/101 [==============================] - 0s 4ms/step - loss: 2.7315e-05 - accuracy: 1.0000
Epoch 23/100
101/101 [==============================] - 0s 4ms/step - loss: 2.4582e-05 - accuracy: 1.0000
Epoch 24/100
101/101 [==============================] - 0s 4ms/step - loss: 2.2096e-05 - accuracy: 1.0000
Epoch 25/100
101/101 [==============================] - 0s 4ms/step - loss: 2.0026e-05 - accuracy: 1.0000
Epoch 26/100
101/101 [==============================] - 0s 4ms/step - loss: 1.8156e-05 - accuracy: 1.0000
Epoch 27/100
101/101 [==============================] - 0s 4ms/step - loss: 1.6435e-05 - accuracy: 1.0000
Epoch 28/100
101/101 [==============================] - 0s 4ms/step - loss: 1.5017e-05 - accuracy: 1.0000
Epoch 29/100
101/101 [==============================] - 0s 5ms/step - loss: 1.3672e-05 - accuracy: 1.0000
Epoch 30/100
101/101 [==============================] - 0s 4ms/step - loss: 1.2518e-05 - accuracy: 1.0000
Epoch 31/100
101/101 [==============================] - 0s 4ms/step - loss: 1.1464e-05 - accuracy: 1.0000
Epoch 32/100
101/101 [==============================] - 1s 7ms/step - loss: 1.0543e-05 - accuracy: 1.0000
Epoch 33/100
101/101 [==============================] - 0s 4ms/step - loss: 9.6542e-06 - accuracy: 1.0000
Epoch 34/100
101/101 [==============================] - 0s 3ms/step - loss: 8.9329e-06 - accuracy: 1.0000
Epoch 35/100
101/101 [==============================] - 0s 3ms/step - loss: 8.2031e-06 - accuracy: 1.0000
Epoch 36/100
101/101 [==============================] - 0s 4ms/step - loss: 7.6068e-06 - accuracy: 1.0000
Epoch 37/100
101/101 [==============================] - 0s 4ms/step - loss: 7.0225e-06 - accuracy: 1.0000
Epoch 38/100
101/101 [==============================] - 0s 3ms/step - loss: 6.4969e-06 - accuracy: 1.0000
Epoch 39/100
101/101 [==============================] - 0s 3ms/step - loss: 5.9958e-06 - accuracy: 1.0000
Epoch 40/100
101/101 [==============================] - 0s 3ms/step - loss: 5.5737e-06 - accuracy: 1.0000
Epoch 41/100
101/101 [==============================] - 0s 4ms/step - loss: 5.1930e-06 - accuracy: 1.0000
Epoch 42/100
101/101 [==============================] - 0s 3ms/step - loss: 4.8218e-06 - accuracy: 1.0000
Epoch 43/100
101/101 [==============================] - 0s 4ms/step - loss: 4.4705e-06 - accuracy: 1.0000
Epoch 44/100
101/101 [==============================] - 0s 3ms/step - loss: 4.1666e-06 - accuracy: 1.0000
Epoch 45/100
101/101 [==============================] - 0s 4ms/step - loss: 3.8753e-06 - accuracy: 1.0000
Epoch 46/100
101/101 [==============================] - 0s 4ms/step - loss: 3.5956e-06 - accuracy: 1.0000
Epoch 47/100
101/101 [==============================] - 0s 3ms/step - loss: 3.3638e-06 - accuracy: 1.0000
Epoch 48/100
101/101 [==============================] - 0s 3ms/step - loss: 3.1399e-06 - accuracy: 1.0000
Epoch 49/100
101/101 [==============================] - 0s 3ms/step - loss: 2.9278e-06 - accuracy: 1.0000
Epoch 50/100
101/101 [==============================] - 0s 3ms/step - loss: 2.7295e-06 - accuracy: 1.0000
Epoch 51/100
101/101 [==============================] - 0s 3ms/step - loss: 2.5493e-06 - accuracy: 1.0000
Epoch 52/100
101/101 [==============================] - 0s 3ms/step - loss: 2.3768e-06 - accuracy: 1.0000
Epoch 53/100
101/101 [==============================] - 0s 3ms/step - loss: 2.2201e-06 - accuracy: 1.0000
Epoch 54/100
101/101 [==============================] - 0s 3ms/step - loss: 2.0742e-06 - accuracy: 1.0000
Epoch 55/100
101/101 [==============================] - 0s 3ms/step - loss: 1.9416e-06 - accuracy: 1.0000
Epoch 56/100
101/101 [==============================] - 0s 4ms/step - loss: 1.8202e-06 - accuracy: 1.0000
Epoch 57/100
101/101 [==============================] - 0s 4ms/step - loss: 1.7027e-06 - accuracy: 1.0000
Epoch 58/100
101/101 [==============================] - 0s 4ms/step - loss: 1.5941e-06 - accuracy: 1.0000
Epoch 59/100
101/101 [==============================] - 0s 4ms/step - loss: 1.4961e-06 - accuracy: 1.0000
Epoch 60/100
101/101 [==============================] - 0s 4ms/step - loss: 1.4031e-06 - accuracy: 1.0000
Epoch 61/100
101/101 [==============================] - 0s 5ms/step - loss: 1.3158e-06 - accuracy: 1.0000
Epoch 62/100
101/101 [==============================] - 0s 4ms/step - loss: 1.2316e-06 - accuracy: 1.0000
Epoch 63/100
101/101 [==============================] - 0s 4ms/step - loss: 1.1522e-06 - accuracy: 1.0000
Epoch 64/100
101/101 [==============================] - 0s 4ms/step - loss: 1.0871e-06 - accuracy: 1.0000
Epoch 65/100
101/101 [==============================] - 0s 4ms/step - loss: 1.0253e-06 - accuracy: 1.0000
Epoch 66/100
101/101 [==============================] - 0s 4ms/step - loss: 9.5908e-07 - accuracy: 1.0000
Epoch 67/100
101/101 [==============================] - 0s 4ms/step - loss: 9.0406e-07 - accuracy: 1.0000
Epoch 68/100
101/101 [==============================] - 0s 4ms/step - loss: 8.5043e-07 - accuracy: 1.0000
Epoch 69/100
101/101 [==============================] - 0s 4ms/step - loss: 7.9688e-07 - accuracy: 1.0000
Epoch 70/100
101/101 [==============================] - 0s 4ms/step - loss: 7.5119e-07 - accuracy: 1.0000
Epoch 71/100
101/101 [==============================] - 0s 4ms/step - loss: 7.0606e-07 - accuracy: 1.0000
Epoch 72/100
101/101 [==============================] - 0s 4ms/step - loss: 6.6822e-07 - accuracy: 1.0000
Epoch 73/100
101/101 [==============================] - 0s 5ms/step - loss: 6.2425e-07 - accuracy: 1.0000
Epoch 74/100
101/101 [==============================] - 0s 3ms/step - loss: 5.8798e-07 - accuracy: 1.0000
Epoch 75/100
101/101 [==============================] - 0s 3ms/step - loss: 5.5503e-07 - accuracy: 1.0000
Epoch 76/100
101/101 [==============================] - 0s 3ms/step - loss: 5.1992e-07 - accuracy: 1.0000
Epoch 77/100
101/101 [==============================] - 0s 3ms/step - loss: 4.8979e-07 - accuracy: 1.0000
Epoch 78/100

101/101 [==============================] - 0s 3ms/step - loss: 4.6244e-07 - accuracy: 1.0000
Epoch 79/100
101/101 [==============================] - 0s 3ms/step - loss: 4.3650e-07 - accuracy: 1.0000
Epoch 80/100
101/101 [==============================] - 0s 3ms/step - loss: 4.1529e-07 - accuracy: 1.0000
Epoch 81/100
101/101 [==============================] - 0s 3ms/step - loss: 3.8547e-07 - accuracy: 1.0000
Epoch 82/100
101/101 [==============================] - 0s 3ms/step - loss: 3.6335e-07 - accuracy: 1.0000
Epoch 83/100
101/101 [==============================] - 0s 3ms/step - loss: 3.4321e-07 - accuracy: 1.0000
Epoch 84/100
101/101 [==============================] - 0s 3ms/step - loss: 3.2422e-07 - accuracy: 1.0000
Epoch 85/100
101/101 [==============================] - 0s 3ms/step - loss: 3.0478e-07 - accuracy: 1.0000
Epoch 86/100
101/101 [==============================] - 0s 3ms/step - loss: 2.8707e-07 - accuracy: 1.0000
Epoch 87/100
101/101 [==============================] - 0s 3ms/step - loss: 3.5270e-07 - accuracy: 1.0000
Epoch 88/100
101/101 [==============================] - 0s 3ms/step - loss: 2.6197e-07 - accuracy: 1.0000
Epoch 89/100
101/101 [==============================] - 0s 3ms/step - loss: 2.3660e-07 - accuracy: 1.0000
Epoch 90/100
101/101 [==============================] - 0s 3ms/step - loss: 2.2053e-07 - accuracy: 1.0000
Epoch 91/100
101/101 [==============================] - 0s 4ms/step - loss: 2.0743e-07 - accuracy: 1.0000
Epoch 92/100
101/101 [==============================] - 0s 4ms/step - loss: 1.9453e-07 - accuracy: 1.0000
Epoch 93/100
101/101 [==============================] - 0s 3ms/step - loss: 1.8198e-07 - accuracy: 1.0000
Epoch 94/100
101/101 [==============================] - 0s 3ms/step - loss: 1.7261e-07 - accuracy: 1.0000
Epoch 95/100
101/101 [==============================] - 0s 3ms/step - loss: 1.6154e-07 - accuracy: 1.0000
Epoch 96/100
101/101 [==============================] - 0s 3ms/step - loss: 1.5353e-07 - accuracy: 1.0000
Epoch 97/100
101/101 [==============================] - 0s 3ms/step - loss: 1.4527e-07 - accuracy: 1.0000
Epoch 98/100
101/101 [==============================] - 0s 3ms/step - loss: 1.3775e-07 - accuracy: 1.0000
Epoch 99/100
101/101 [==============================] - 0s 3ms/step - loss: 1.2956e-07 - accuracy: 1.0000
Epoch 100/100
101/101 [==============================] - 0s 3ms/step - loss: 1.2194e-07 - accuracy: 1.0000

In [13]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

34/34 - 0s - loss: 0.0083 - accuracy: 0.9972 - 203ms/epoch - 6ms/step
Loss: 0.008251693099737167, Accuracy: 0.9971910119056702

In [14]:
# Export our model to HDF5 file
model_filename = "loan_apps_layers.h5"
nn.save("loan_apps_layers.h5")

C:\Users\hspek\anaconda3\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(